ports:
  - port: 8080
tasks:
  - command: >
        pip install -r requirements.txt &&
        cp .env.example .env &&
        sed -i 's/ALLOWED_HOSTS.*/ALLOWED_HOSTS=\*/' .env &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8080
